/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Transaction } from '../models/transaction';
export interface Account {
  accountNumber?: number;
  amount?: GLfloat;
  currency?: string;
  dateOfCreation?: string;
  iban?: string;
  id?: number;
  isMain?: boolean;
  transactions?: Array<Transaction>;
  userId: number;
}
