/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Account } from '../models/account';
export interface Transaction {
  accounts?: Array<Account>;
  amount: GLfloat;
  currency: string;
  dateOfCreation?: string;
  dateOfTransaction?: string;
  destinationBIC?: string;
  destinationIban: string;
  destinationName: string;
  id?: number;
  purposeOfUse: string;
  sourceIban: string;
  sourceName?: string;
}
