/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Transaction } from '../models/transaction';
import { transactionsGet } from '../fn/transactions/transactions-get';
import { TransactionsGet$Params } from '../fn/transactions/transactions-get';

@Injectable({ providedIn: 'root' })
export class TransactionsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `transactionsGet()` */
  static readonly TransactionsGetPath = '/transactions';

  /**
   * Returns all transactions.
   *
   * Optional extended description in CommonMark or HTML
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `transactionsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  transactionsGet$Response(params?: TransactionsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Transaction>>> {
    return transactionsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Returns all transactions.
   *
   * Optional extended description in CommonMark or HTML
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `transactionsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  transactionsGet(params?: TransactionsGet$Params, context?: HttpContext): Observable<Array<Transaction>> {
    return this.transactionsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Transaction>>): Array<Transaction> => r.body)
    );
  }

}
