/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Transaction } from '../../models/transaction';

export interface UsersUserIdAccountsAccountIdTransactionsGet$Params {
  'users-id': number;
  'accounts-id': number;
}

export function usersUserIdAccountsAccountIdTransactionsGet(http: HttpClient, rootUrl: string, params: UsersUserIdAccountsAccountIdTransactionsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Transaction>>> {
  const rb = new RequestBuilder(rootUrl, usersUserIdAccountsAccountIdTransactionsGet.PATH, 'get');
  if (params) {
    rb.path('users-id', params['users-id'], {});
    rb.path('accounts-id', params['accounts-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Transaction>>;
    })
  );
}

usersUserIdAccountsAccountIdTransactionsGet.PATH = '/users/{user-id}/accounts/{account-id}/transactions';
