/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Account } from '../models/account';
import { Role } from '../models/role';
export interface User {
  accounts?: Array<Account>;
  dateOfBirth: string;
  dateOfCreation?: string;
  email?: string;
  firstName: string;
  id?: number;
  lastName: string;
  password?: string;
  phone?: string;
  role: Role;

  /**
   * User Status
   */
  userStatus?: number;
}
